server:
  port: 7777
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${HM_DB_URL}
    username: ${HM_DB_USERNAME}
    password: ${HM_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    include:
      - common

logging:
  level:
    kr.co.houmuch: INFO