version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster
        environment:
          JVM_OPTS: -Xmx2048m -Xms2048m
          HM_OPEN_API_KEY: $HM_OPEN_API_KEY
          HM_DB_URL: $HM_DB_URL
          HM_DB_USERNAME: $HM_DB_USERNAME
          HM_DB_PASSWORD: $HM_DB_PASSWORD
          HM_SLACK_WEBHOOK_TOKEN: $HM_SLACK_WEBHOOK_TOKEN
          HM_NAVER_CLIENT_ID: $HM_NAVER_CLIENT_ID
          HM_NAVER_CLIENT_SECRET: $HM_NAVER_CLIENT_SECRET
          GITHUB_USERNAME: $GITHUB_USERNAME
          GITHUB_PASSWORD: $GITHUB_PASSWORD
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test -Pprofile=prod
      - run: ./gradlew build -Pprofile=prod
      - run: echo $GITHUB_PASSWORD | docker login https://ghcr.io -u youspend8 --password-stdin
      - run: docker build -t ghcr.io/houmuch-kr/api:1.0.0 -f deploy/Dockerfile .
      - run: docker push ghcr.io/houmuch-kr/api:1.0.0

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $DEV_SSH_USER@$DEV_SSH_HOST '
              docker pull ghcr.io/houmuch-kr/api:1.0.0
              docker-compose -f "houmuch/docker-compose.yml" up -d
            '

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
